[project]
name = "test-work"
version = "0.1.0"
description = ""
authors = [
    {name = "Igor Sverchkov",email = "knjaz1989@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi (>=0.141.1,<0.142.0)",
    "uvicorn (>=0.53.0,<0.54.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
